"""Agrego tabla Auditoría

Revision ID: 3c6b35c70f24
Revises: 1d9f743b7319
Create Date: 2024-04-26 08:47:52.202146

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c6b35c70f24'
down_revision = '1d9f743b7319'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tabla_origen', sa.String(), nullable=False),
    sa.Column('registro_id', sa.Integer(), nullable=False),
    sa.Column('operacion', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.Column('valores_originales', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valores_nuevos', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_auditoria_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoria'))
    )
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Float(precision=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Float(precision=2),
               type_=sa.REAL(),
               existing_nullable=False)

    op.drop_table('auditoria')
    # ### end Alembic commands ###
