"""Quito temporalmente not null de version

Revision ID: 48d5daa742c6
Revises: 3c6b35c70f24
Create Date: 2024-04-26 18:52:10.321219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48d5daa742c6'
down_revision = '3c6b35c70f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.REAL(),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.REAL(),
               existing_nullable=False)

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.alter_column('version',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
