"""empty message

Revision ID: 9c1db37774a1
Revises: 645b1ffdb876
Create Date: 2024-05-13 19:15:18.004717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c1db37774a1'
down_revision = '645b1ffdb876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paises'))
    )
    op.create_table('timezones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('pais', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pais'], ['paises.id'], name=op.f('fk_timezones_pais_paises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timezones'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tz_info', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_users_tz_info_timezones'), 'timezones', ['tz_info'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_tz_info_timezones'), type_='foreignkey')
        batch_op.drop_column('tz_info')

    op.drop_table('timezones')
    op.drop_table('paises')
    # ### end Alembic commands ###
