"""empty message

Revision ID: c623bbf097ac
Revises: 8cb88936b151
Create Date: 2024-05-01 19:11:59.633458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c623bbf097ac'
down_revision = '8cb88936b151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tienda_asociada_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('item_asociado_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_column('item_asociado_id')
        batch_op.drop_column('tienda_asociada_id')

    # ### end Alembic commands ###
