"""Cambio previo y agrego User

Revision ID: e8c4117d1638
Revises: 6df63a05ed4e
Create Date: 2024-04-17 10:46:35.554881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c4117d1638'
down_revision = '6df63a05ed4e'
branch_labels = None
depends_on = None


def upgrade():

    op.execute("DELETE FROM stores")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=60), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=60), nullable=False),
                    sa.Column('password', sa.String(
                        length=60), nullable=False),
                    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
                    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
                    )
    # op.drop_table('tag_model')
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f(
            'fk_stores_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f(
            'fk_stores_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('tag_model',
                    sa.Column('id', sa.INTEGER(), nullable=False),
                    sa.Column('name', sa.VARCHAR(length=60), nullable=False),
                    sa.PrimaryKeyConstraint('id', name='pk_tag_model')
                    )
    op.drop_table('users')
    op.drop_table('tags')
    # ### end Alembic commands ###
